name: Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ecs:
    name: ECS
    uses: juban/.github/.github/workflows/ecs.yml
    with:
      php_version: '8.0'
  phpstan:
    name: PHPStan
    uses: juban/.github/.github/workflows/phpstan.yml
    with:
      php_version: '8.0'
  codecept:
    name: Codeception
    needs: [ ecs, prettier, phpstan ]
    uses: juban/.github/.github/workflows/codecept.yml
    with:
      php_versions: '8.0'
